### ISSUE TITLE
codegen cft can generate invalid cloudformation stack names

### ISSUE THREAD

**Issue by ckrough** [awslabs/aws-service-operator#103]
The `cft` codegen template specifies that the Cloudformation Stack Name should be based on the asset `Name`. AWS Resource types have different naming rules. This creates a situation where an asset resource name could be valid for it's own type, but not for the cloudformation stack that manages it. 

For example  `1234-foo` is a valid S3 bucket name, but `1234-foo` is not a valid Cloudformation StackName.

This spec:
```
apiVersion: operator.aws/v1alpha1
kind: S3Bucket
metadata:
  name: 1234-foo
  namespace: aws-operator
spec:
  versioning: true
  accessControl: Private
  logging:
    enabled: false
    prefix: "archive"
```

Will cause the following error:
```
Value '1234-foo' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]
```

offending code: https://github.com/awslabs/aws-service-operator/blob/master/code-generation/pkg/codegen/assets/cft.go.templ#L64-L77
