### ISSUE TITLE
Add Better Tagging Support Across all Resources

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#118]
Would be nice to have a mechanism for setting tags not just on the CFT stack but also on the resources. Should be implemented as a single structure for all Objects to make parsing easy.

```yaml
spec:
  tags:
  - key: OrganizationalUnit
    value: device-management
```
