### ISSUE TITLE
Configmaps for services other than s3 missing

### ISSUE THREAD

**Issue by jgryszko** [awslabs/aws-service-operator#131]
Is it planned to create config maps for other services than s3 (sqs, sns ...), or is there any reason, why it was omitted? Looking for areas to contribute...

**Comment by christopherhein** [comment]
There is not a reason, this would be a great first issue :)

**Comment by ivangrynkoring** [comment]
@christopherhein Any update on this? I've tried to add corresponding additional resource to sqsqueue.yaml model and rebuild aws-service-operator but it still doesn't create configmap for sqs.
Basically what I tried so far:
```
  additionalResources:
    configMaps:
    - name: sqsCM
      data:
      - key: queueARN
        value: "{{.Obj.Output.QueueARN}}"
      - key: queueName
        value: "{{.Obj.Output.QueueName}}"
      - key: queueURL
        value: "{{.Obj.Output.QueueURL}}"
```
and then run "make rebuld" to regenerate and build code. Am I miss something?

**Comment by ivanich** [comment]
@christopherhein Any update on this? I've tried to add corresponding additional resource to sqsqueue.yaml model and rebuild aws-service-operator but it still doesn't create configmap for sqs.
Basically what I tried so far:

```
  additionalResources:
    configMaps:
    - name: sqsCM
      data:
      - key: queueARN
        value: "{{.Obj.Output.QueueARN}}"
      - key: queueName
        value: "{{.Obj.Output.QueueName}}"
      - key: queueURL
        value: "{{.Obj.Output.QueueURL}}"
```

and then run "make rebuld" to regenerate and build code. Am I miss something?
