### ISSUE TITLE
US-East S3 Buckets Get Invalid External Names

### ISSUE THREAD

**Issue by kellinm** [awslabs/aws-service-operator#135]
Master Branch, Commit Hash 3f46646846252de2e9e7fdd25922e7d7ce2b5522.

Steps to Reproduce:

**Create file s3bucket.yaml**

```yaml
apiVersion: service-operator.aws/v1alpha1
kind: S3Bucket
metadata:
  name: kellin-first-bucket
spec:
  versioning: true
  accessControl: PublicRead
  website:
    enabled: true
    indexPage: index.html
    errorPage: 500.html
  logging:
    enabled: false
    prefix: "archive"
```

Apply this to test the storage creation.

```sh
$ kubectl apply -f s3bucket.yaml
$ kubectl describe service kellin-first-bucket
Name:              kellin-first-bucket
Namespace:         default
Labels:            <none>
Annotations:       <none>
Selector:          <none>
Type:              ExternalName
IP:                
External Name:     kellin-first-bucket.s3-us-east-1.amazonaws.com
Port:              <unset>  443/TCP
TargetPort:        443/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
$ kubectl get service kellin-first-bucket -o wide
NAME                  TYPE           CLUSTER-IP   EXTERNAL-IP                                      PORT(S)   AGE       SELECTOR
kellin-first-bucket   ExternalName   <none>       kellin-first-bucket.s3-us-east-1.amazonaws.com   443/TCP   21m       <none> 
```

[The AWS S3 documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro) states this:

> If your bucket is in the US East (N. Virginia) Region, you must use the http://s3.amazonaws.com/bucket endpoint.

The **External Name** is not a valid URL to the bucket.  The bucket does get created, however, any node attempting to reach it will get a faulty url.

I would expect the AWS Operator Service to follow the documented behavior. (Or, for the documented behavior to be standardized so that US-East-1 works like everywhere else.)
