### ISSUE TITLE
Need support for lists in model

### ISSUE THREAD

**Issue by sepulworld** [awslabs/aws-service-operator#146]
Need support for lists in model

This currently doesn't work:
```
body:
    schema:
      type: object
      properties:
      - key: VpcSecurityGroupIds
        type: list
        description: |
          A list of VPC security group IDs. If your cache cluster isn't in a VPC, specify the CacheSecurityGroupNames property instead.
        structKey: VpcSecurityGroupIds
        templateKey: VpcSecurityGroupIds
```

https://github.com/kubernetes/gengo/blob/master/types/types.go#L403-L490 -- Here is list of builtin types supported in gogen, can we extend this easily?
