### ISSUE TITLE
extraEnv parameter in Helm Chart doesn't render correctly

### ISSUE THREAD

**Issue by mattparkes** [awslabs/aws-service-operator#150]
Setting Environment Variables for the Deployment using `extraEnv` doesn't work:

```
extraEnv:
  - name: my_env
    value: my_value
```

`helm template ./aws-service-operator/ -f test.yaml`

Renders as:

```
spec:
  env:
  - name: 0
     value: map[name:my_env value:my_value]
```
