### ISSUE TITLE
Using wrong region in cloud formation headers

### ISSUE THREAD

**Issue by lightsofapollo** [awslabs/aws-service-operator#155]
I am running the example step:

```
kubectl apply -f examples/cloudformationtemplates
```

My operator is coming up okay but in the logs I see many errors like the following:

```
time="2019-01-21T12:22:58Z" level=error msg="error uploading cloudformation" error="AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2'\n\tstatus code: 400, request id: 1D9A7AE140E06315, host id: plrfrXdM8Bh6EOZ6x9b2nOg+YcwN1mjip+ZxzuvuRuWWwTYLRK4cIqqXm+Hmalw0le4KSmeC/y0=" hostname=aws-service-operator-bff9678bd-v9k2n
```

NOTE: I have configured my resources on east-1 so it's a non starter to try things out on west-2 I am hoping I made some silly error.

abbreviated configuration

```yaml
  - kind: Deployment
    apiVersion: apps/v1beta1
    metadata:
      name: aws-service-operator
      namespace: aws-service-operator
    spec:
      replicas: 1
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::xxxx:role/aws-service-operator.conduitvc-kubernetes.aws.conduit.ventures
          labels:
            app: aws-service-operator
        spec:
          serviceAccountName: aws-service-operator
          containers:
            - name: aws-service-operator
              image: awsserviceoperator/aws-service-operator:v0.0.1-alpha2
              imagePullPolicy: Always
              # I tired adding this without any results.
              env:
                - name: AWS_REGION
                  value: us-east-1
              args:
                - server
                - --cluster-name=conduitvc-kubernetes
                - --region=us-east-1
                - --account-id=229055845648

```
