### ISSUE TITLE
Adding S3Bucket Resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#20]
This should create s3buckets and be formatted like so:

```yaml
apiVersion: operator.aws/v1alpha1
kind: S3Bucket
metadata:
  name: test-bucket
spec:
  bucketName: test-bucket-name
  versioning: false
  logging:
    enabled: false
    prefix: "archive"
```
