### ISSUE TITLE
Issue creating sns subscription with sms protocol

### ISSUE THREAD

**Issue by computeracer** [awslabs/aws-service-operator#204]
When I create an sns subscription with the sms protocol I get this error message:

`time="2019-08-21T14:45:13Z" level=error msg="error creating snssubscription 'example-subscription-name'" error="template: templating:1:3: executing \"templating\" at <call .Helpe ││ rs.GetSQSQueueByName .Config .Obj.Spec.Endpoint .Obj.Namespace>: error calling call: sqsqueues.service-operator.aws \"+15182563413\" not found" hostname=aws-service-operator-5f4d ││ 7dd8db-w9rvw`

Here is my spec file:

```
---
apiVersion: service-operator.aws/v1alpha1
kind: SNSTopic
metadata:
  name: example-sns-topic

---
apiVersion: service-operator.aws/v1alpha1
kind: SNSSubscription
metadata:
  name: example-subscription-name
spec:
  topicName: example-sns-topic
  protocol: sms
  endpoint: "+11234567890"
```

Any ideas on what I am doing wrong?

Thank you.
