### ISSUE TITLE
Add DynamoDB resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#22]
Allows you to create Dynamodb resources using an operator

```yaml
apiVersion: operator.aws/v1alpha1
kind: DynamoDB
metadata:
  name: chrishein-dynamodb-table-2
spec:
  tableName: chrishein-dynamodb-table-2
  hashAttribute:
    name: user_id
    type: S
  rangeAttribute:
    name: created_at
    type: S
  readCapacityUnits: 5
  writeCapacityUnits: 5
```
