### ISSUE TITLE
Adding SQS resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#24]
Creates SQS Queues Using CRDS like this:
```yaml
apiVersion: operator.aws/v1alpha1
kind: SQS
metadata:
  name: chrishein-test-sqs-1
spec:
  contentBasedDeduplication: false
  delaySeconds: 1
  usedeadletterQueue: false
```
