### ISSUE TITLE
Create SNS Topic Resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#33]
Should create an `SNSTopic`, this is meant to be used with a `SNSTopicSubscription`. `TopicName` for the CFT should be a UUID resource type after issue #34  is finished

```yaml
apiVersion: operator.aws/v1alpha1
kind: SNSTopic
metadata:
  name: sns-topic
spec:
  displayName: sns-topic
```
