### ISSUE TITLE
Add SNS Subscription Resource 

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#36]
This should take an `SNSTopic` resource and bind it using a Subscription, this
should be able to both reference local SQS resource types as well as non-SQS
types.

```yaml
apiVersion: operator.aws/v1alpha1
kind: SNSSubscription
metadata:
  name: sns-sqs-subscription
spec:
  snsTopicName: sns-topic
  subject:
    protocol: sqs
    name: sqs-queue
    # endpoint: optional
```
