### ISSUE TITLE
Create ElastiCache Resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#37]
This resource will allow a developer to create an ElastiCache instance using
the CRD model, it should be generic enough to support both memcached and redis.

```yaml
apiVersion: operator.aws/v1alpha1
kind: ElastiCache
metadata:
  name: elasticache
spec:
  autoMinorVersionUpgrade: true
  azMode: # (single-az|cross-az) only memcached
  nodeType: cache.m3.medium
  engine: # (memcached|redis)
  version: 4.0.10
  cacheNodes: 3
  tags:
  - name: Usage
    value: caching
```
