### ISSUE TITLE
Add the Ability to Provision an ECR registry

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#45]
This makes it possible to get an ECR registry for a project while using the operator.

```yaml
apiVersion: operator.aws/v1alpha1
kind: ECR
metadata:
  name: test-app
spec:
  lifecyclePolicy: |
    # ...
  repositoryPolicy: |
    # ...
```
