### ISSUE TITLE
Create SQS Queue Resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#7]
Should create SQS Queues and be formatted:

```yaml
apiVersion: operator.aws/v1alpha1
kind: SQS
metadata:
  name: chrishein-test-sqs-1
spec:
  contentBasedDeduplication: false
  delaySeconds: 1
  usedeadletterQueue: false
```
