### ISSUE TITLE
Add Support For Creating S3 Bucket Websites

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#71]
This will add params to allow you to setup a static site using the CRD.

```yaml
spec:
  website:
    enabled: true
    indexPage: index.html
    errorPage: error.html
```

I will implement redirect and routing rules in another issue.
