### ISSUE TITLE
Create Cloudformation Resources

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#8]
Should upload the raw template to the S3 bucket setup when creating the
operator and be formatted like so

```yaml
apiVersion: operator.aws/v1alpha1
kind: CloudFormationTemplate
metadata:
  name: s3bucket
  data:
    key: s3bucket.yaml
    template: |
      # ... Raw JSON or YAML template
```
