### ISSUE TITLE
Add Support for API Gateway Resource

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#86]
This will add support for adding an API Gateway with NLB based services.

```yaml
apiVersion: operator.aws/v1alpha1
kind: APIGateway
metadata:
  name: example-apigateway
spec:
  # ??
```

@tantona.
