### ISSUE TITLE
Add Support for Lambda function

### ISSUE THREAD

**Issue by christopherhein** [awslabs/aws-service-operator#99]
This would add support for being able to deploy a lambda function directly from `kubectl`. This should use the Lambda CFN resource and will allow you to specify a configmap reference, or s3bucket for the actual code.

```yaml
apiVersion: service-operator.aws/v1alpha1
kind: LambdaFunction
metadata:
  name: example-lambda-function
spec:
  deadLetter:
    name: example-sns-deadletter # will convert this into an ARN
  description: |
    Anything about the function that is necessary.
  tags:
  code: 
    handler: index.handle
    env:
    - name: ENV
      value: staging
    runtime: nodejs # https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime
    resources:
      limit:
        memory: 128
        timout: 3
        concurrency: 3
    inline: | # this uses the zipfile construct
      print "hi"
    configMapKeyRef:
      name: lambda-function-code
      key: binary-data-type-key
    s3bucket:
      name: example-s3bucket # reference S3Bucket kind or existing bucket
      key: example-function.zip
      version: # optional
```
